//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/equipoUs", ReplyAction="http://tempuri.org/IService1/equipoUsResponse")]
        string equipoUs(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/equipoUs", ReplyAction="http://tempuri.org/IService1/equipoUsResponse")]
        System.Threading.Tasks.Task<string> equipoUsAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/puntajeUs", ReplyAction="http://tempuri.org/IService1/puntajeUsResponse")]
        int puntajeUs(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/puntajeUs", ReplyAction="http://tempuri.org/IService1/puntajeUsResponse")]
        System.Threading.Tasks.Task<int> puntajeUsAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/apodoUs", ReplyAction="http://tempuri.org/IService1/apodoUsResponse")]
        string apodoUs(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/apodoUs", ReplyAction="http://tempuri.org/IService1/apodoUsResponse")]
        System.Threading.Tasks.Task<string> apodoUsAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuario", ReplyAction="http://tempuri.org/IService1/usuarioResponse")]
        bool usuario(string nombre, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuario", ReplyAction="http://tempuri.org/IService1/usuarioResponse")]
        System.Threading.Tasks.Task<bool> usuarioAsync(string nombre, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarUsuario", ReplyAction="http://tempuri.org/IService1/registrarUsuarioResponse")]
        bool registrarUsuario(string nombre, string contrasena, string apodo, string equipoPreferido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarUsuario", ReplyAction="http://tempuri.org/IService1/registrarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> registrarUsuarioAsync(string nombre, string contrasena, string apodo, string equipoPreferido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizarPuntaje", ReplyAction="http://tempuri.org/IService1/actualizarPuntajeResponse")]
        bool actualizarPuntaje(int puntaje, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizarPuntaje", ReplyAction="http://tempuri.org/IService1/actualizarPuntajeResponse")]
        System.Threading.Tasks.Task<bool> actualizarPuntajeAsync(int puntaje, string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApplication3.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApplication3.ServiceReference1.IService1>, WindowsFormsApplication3.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string equipoUs(string nombre) {
            return base.Channel.equipoUs(nombre);
        }
        
        public System.Threading.Tasks.Task<string> equipoUsAsync(string nombre) {
            return base.Channel.equipoUsAsync(nombre);
        }
        
        public int puntajeUs(string nombre) {
            return base.Channel.puntajeUs(nombre);
        }
        
        public System.Threading.Tasks.Task<int> puntajeUsAsync(string nombre) {
            return base.Channel.puntajeUsAsync(nombre);
        }
        
        public string apodoUs(string nombre) {
            return base.Channel.apodoUs(nombre);
        }
        
        public System.Threading.Tasks.Task<string> apodoUsAsync(string nombre) {
            return base.Channel.apodoUsAsync(nombre);
        }
        
        public bool usuario(string nombre, string contrasena) {
            return base.Channel.usuario(nombre, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> usuarioAsync(string nombre, string contrasena) {
            return base.Channel.usuarioAsync(nombre, contrasena);
        }
        
        public bool registrarUsuario(string nombre, string contrasena, string apodo, string equipoPreferido) {
            return base.Channel.registrarUsuario(nombre, contrasena, apodo, equipoPreferido);
        }
        
        public System.Threading.Tasks.Task<bool> registrarUsuarioAsync(string nombre, string contrasena, string apodo, string equipoPreferido) {
            return base.Channel.registrarUsuarioAsync(nombre, contrasena, apodo, equipoPreferido);
        }
        
        public bool actualizarPuntaje(int puntaje, string usuario) {
            return base.Channel.actualizarPuntaje(puntaje, usuario);
        }
        
        public System.Threading.Tasks.Task<bool> actualizarPuntajeAsync(int puntaje, string usuario) {
            return base.Channel.actualizarPuntajeAsync(puntaje, usuario);
        }
    }
}
